[package]
name = "winit_input_helper"
repository = "https://github.com/rukai/winit_input_helper"
version = "0.6.0"
edition = "2018"
authors = ["Rukai <rubickent@gmail.com>"]
license = "MIT"
description = "Processes winit events, allowing input state to be queried at any time."
keywords = ["winit", "input", "helper", "state", "cache"]
categories = ["game-engines", "os", "gui"]

[dependencies]
winit = "0.22.0"
